# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzO5k2m_6q0l89jaJ5jBTo8_EJj-3pCK
"""

import pandas as pd
# Load the Heart_disease dataset
train_data = pd.read_csv('heart_disease_uci.csv')
# Display the first few rows of the training data
print("Training data:")
print(train_data.head())
# Get the shape of the training data (number of rows, number of columns)
print("\nShape of training data:", train_data.shape)
# Get information about the columns and data types in the training data
print("\nTraining data information:")
print(train_data.info())
# Get summary statistics of the numeric columns in the training data
print("\nSummary statistics of training data:")
print(train_data.describe())
# Display the column names in the training data
print("Columns in training data:")
print(train_data.columns)
# Check for missing values in the training data
print("\nMissing values in training data:")
print(train_data.isnull().sum())
# Count the number of unique values in each column of the training data
print("\nUnique value counts in training data:")
print(train_data.nunique())
# Check the data types of each column in the training data
print("\nData types in training data:")
print(train_data.dtypes)
# Check the distribution of other categorical variables
print("\nSex distribution:")
print(train_data['sex'].value_counts())
print("\nChest pain type distribution:")
print(train_data['cp'].value_counts())
print("\nFasting blood sugar distribution:")
print(train_data['fbs'].value_counts())
print("\nResting electrocardiographic results distribution:")
print(train_data['restecg'].value_counts())
print("\nExercise induced angina distribution:")
print(train_data['exang'].value_counts())
print("\nNumber of major vessels distribution:")
print(train_data['ca'].value_counts())
print("\nThalassemia distribution:")
print(train_data['thal'].value_counts())
# Get statistical information for numeric columns
numeric_columns = train_data.select_dtypes(include='number')
statistics = numeric_columns.describe()
# Print the statistical information
print(statistics)